#!/bin/bash

# Generated by wiktts.trainer
# Version 0.0.4
# Date 2016-05-24

BASE="{BASE}"
TRAIN="{BASE}.train"
TEST="{BASE}.test"

LOG="{BASE}.phonetisaurus.log"
CORPUS="{BASE}.corpus"
ARPA="{BASE}.arpa"
MODEL="{BASE}.fst"
PREFIX="{BASE}"
WORDS="$PREFIX.words"
HYP="$PREFIX.hyp"
REF="$PREFIX.ref"
ERPY="{ERPY}"
NGRAMORDER="{NGRAMORDER}"
SMOOTHING="{SMOOTHING}"

### NORMALLY YOU SHOULD NOT NEED TO EDIT BELOW THIS LINE

usage() {{
    echo ""
    echo "$ bash $0 train"
    echo "$ bash $0 test"
    echo "$ bash $0 clean"
    echo ""
    echo "Parameters:"
    echo "  ngramorder: {NGRAMORDER}"  
    echo "  smoothing: {SMOOTHING}"  
    echo ""
    exit 2
}}

run_train() {{
    START=`date +%s`
    echo "" >> $LOG
    echo "==============================" >> $LOG
    echo "Training model..." | tee -a $LOG
    echo "" >> $LOG
    
    echo "Calling phonetisaurus-align..."
    phonetisaurus-align --input=$TRAIN --ofile=$CORPUS --seq1_del=false 2>> $LOG >> $LOG
    if [ ! -e "$CORPUS" ]
    then
        echo "[ERROR] CORPUS file $CORPUS not created. Aborting."
        exit 1
    fi
    echo "Calling phonetisaurus-align... done"
    echo ""
    
    echo "Calling estimate-ngram..."
    estimate-ngram -t $CORPUS -o $NGRAMORDER -s $SMOOTHING -wl $ARPA 2>> $LOG >> $LOG
    if [ ! -e "$ARPA" ]
    then
        echo "[ERROR] ARPA file $ARPA not created. Aborting."
        exit 1
    fi
    echo "Calling estimate-ngram... done"
    echo ""

    echo "Calling phonetisaurus-arpa2wfst..."
    phonetisaurus-arpa2wfst --lm=$ARPA --ofile=$MODEL 2>> $LOG >> $LOG
    if [ ! -e "$MODEL" ]
    then
        echo "[ERROR] MODEL file $MODEL not created. Aborting."
        exit 1
    fi
    echo "Calling phonetisaurus-arpa2wfst... done"
    echo ""

    END=`date +%s`
    DIFF=`echo "$END - $START" | bc`
    echo "" >> $LOG
    echo "Training model... done in $DIFF s" | tee -a $LOG
    echo "==============================" >> $LOG
    echo "" >> $LOG
}}

run_test() {{
    if [ ! -e "$MODEL" ]
    then
        echo "[ERROR] To test you need file $MODEL (i.e., train first)"
        exit 1
    fi

    # TODO detect duplicate entries and concatenate:
    #
    # in .test:
    #
    # abc \t 001 002 003
    # abc \t 001 002 004
    #
    # should become in .ref :
    #
    # abc \t 001 002 003 \t 001 002 004
    #
    cp $TEST $REF
    cat $TEST | awk 'BEGIN{{FS="\t"}}{{print $1}}' > $WORDS
    phonetisaurus-g2pfst --model=$MODEL --wordlist=$WORDS > $HYP
    python $ERPY $HYP $REF
}}

run_clean() {{
    rm -f $CORPUS
    rm -f $ARPA
    rm -f $MODEL
    rm -f $WORDS
    rm -f $HYP
    rm -f $REF
}}

if [ "$#" -lt 1 ]
then
    usage
fi
COMMAND=$1

if [ "$COMMAND" == "clean" ]
then
    run_clean
    exit 0
fi

if [ "$COMMAND" == "train" ]
then
    rm -f $LOG
    run_train
    exit 0
fi

if [ "$COMMAND" == "test" ]
then
    run_test
    exit 0
fi

usage



