#!/bin/bash

# Generated by wiktts.trainer
# Version 0.0.4
# Date 2016-05-24

BASE="{BASE}"
TRAIN="{BASE}.train"
TEST="{BASE}.test"

LOG="{BASE}.sequitur.log"
MODELPREFIX="{BASE}.model."
MAXLEVEL="{MAXLEVEL}"
DEVEL="{DEVEL}%"

### NORMALLY YOU SHOULD NOT NEED TO EDIT BELOW THIS LINE

usage() {{
    echo ""
    echo "$ bash $0 train [LEVEL [--only]]"
    echo "$ bash $0 test [LEVEL]"
    echo "$ bash $0 clean"
    echo ""
    echo "Parameters:"
    echo "  maxlevel: {MAXLEVEL}"  
    echo "  devel: {DEVEL}%"
    echo ""
    exit 2
}}

run_train_level() {{
    START=`date +%s`
    L=$1
    M="$MODELPREFIX""$L"
    R=""
    if [ "$L" -gt 1 ]
    then
        P=$((L - 1))
        PREVM="$MODELPREFIX""$P"
        if [ ! -e "$PREVM" ]
        then
            echo "[ERROR] To train at level $L you need file $PREVM (i.e., train at level $P first)"
            exit 1
        fi
        R="--model $PREVM --ramp-up"
    fi
    echo "" >> $LOG
    echo "==============================" >> $LOG
    echo "Training model $L..." | tee -a $LOG
    echo "" >> $LOG
    g2p.py --devel "$DEVEL" --train "$TRAIN" $R --write-model "$M" 2>> $LOG >> $LOG
    END=`date +%s`
    DIFF=`echo "$END - $START" | bc`
    echo "" >> $LOG
    echo "Training model $L... done in $DIFF s" | tee -a $LOG
    echo "==============================" >> $LOG
    echo "" >> $LOG
}}

run_test() {{
    L=$1
    M="$MODELPREFIX""$L"
    if [ ! -e "$M" ]
    then
        echo "[ERROR] To test at level $L you need file $M (i.e., train at level $L first)"
        exit 1
    fi
    g2p.py --model "$M" --test "$TEST"
}}

run_clean() {{
    rm -f $MODELPREFIX*
}}

if [ "$#" -lt 1 ]
then
    usage
fi
COMMAND=$1

LEVEL=$MAXLEVEL
if [ "$#" -ge 2 ]
then
    LEVEL=$2
fi

if [ "$COMMAND" == "clean" ]
then
    run_clean
    exit 0
fi

if [ "$COMMAND" == "train" ]
then
    rm -f $LOG
    ONLY=0
    if [ "$#" -ge 3 ] && [ "$3" == "--only" ]
    then
        ONLY=1
    fi
    if [ "$ONLY" -eq 1 ]
    then
        run_train_level $LEVEL
    else
        for ((i=1; i <= LEVEL; ++i))
        do
            run_train_level $i
        done
    fi
    exit 0
fi

if [ "$COMMAND" == "test" ]
then
    run_test $LEVEL
    exit 0
fi

usage
